---
name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: free disk space
        run: |
          # sudo swapoff -a
          # sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          echo "##################"
          df -h
          echo "##################"
          free -m

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: set go version
        id: go
        run: echo "::set-output name=version::$(cat .go-version)"

      - name: Set up Go
        uses: actions/setup-go@v3
        # with:
        #   go-version-file: 'go.mod'
        #   cache: true
        with:
          go-version: ${{ steps.go.outputs.version }}

      - name: Import GPG key
        id: import_gpg
        uses: paultyng/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3.2.0
        with:
          version: latest
          args: release --rm-dist --timeout 2h # --parallelism 2 
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
